/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f3fe",
        "secondary-fixed-dim": "#81d8a8",
        "surface-container": "#ededf8",
        "on-tertiary-container": "#ffd4c5",
        "inverse-surface": "#2e3039",
        "on-primary-fixed": "#00174d",
        "surface-container-highest": "#e2e1ed",
        "tertiary-container": "#ad3b00",
        "on-background": "#191b23",
        background: "#f4f6f8",
        "surface-dim": "#d9d9e4",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#002112",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f0fb",
        "on-tertiary-fixed": "#380d00",
        "surface-variant": "#e2e1ed",
        "on-error": "#ffffff",
        "on-secondary-container": "#0c7149",
        "inverse-primary": "#b5c4ff",
        "text-main": "#0f172a",
        "surface-tint": "#1353d8",
        "on-surface": "#191b23",
        "on-primary-container": "#d4dcff",
        tertiary: "#852b00",
        "secondary-fixed": "#9df5c3",
        "on-tertiary-fixed-variant": "#802a00",
        "on-secondary-fixed-variant": "#005233",
        "surface-container-high": "#e7e7f3",
        "tertiary-fixed": "#ffdbcf",
        error: "#ba1a1a",
        primary: "#003fb1",
        "on-secondary": "#ffffff",
        "text-muted": "#64748b",
        "primary-fixed-dim": "#b5c4ff",
        "outline-variant": "#c3c5d7",
        "on-surface-variant": "#434654",
        "on-error-container": "#93000a",
        surface: "#ffffff",
        "primary-container": "#1a56db",
        "primary-fixed": "#dbe1ff",
        "surface-bright": "#faf8ff",
        secondary: "#016c45",
        outline: "#737686",
        "on-primary": "#ffffff",
        "secondary-container": "#9af2c0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        margin: "2rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-lg": ["Inter"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
