/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f3fe",
        "secondary-fixed-dim": "#81d8a8",
        "surface-container": "#ededf8",
        "on-tertiary-container": "#ffd4c5",
        "inverse-surface": "#2e3039",
        "on-primary-fixed": "#00174d",
        "surface-container-highest": "#e2e1ed",
        "tertiary-container": "#ad3b00",
        "on-background": "#191b23",
        background: "#f4f6f8",
        "surface-dim": "#d9d9e4",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#002112",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f0fb",
        "on-tertiary-fixed": "#380d00",
        "surface-variant": "#e2e1ed",
        "on-error": "#ffffff",
        "on-secondary-container": "#0c7149",
        "inverse-primary": "#b5c4ff",
        "text-main": "#0f172a",
        "surface-tint": "#1353d8",
        "on-surface": "#191b23",
        "on-primary-container": "#d4dcff",
        tertiary: "#852b00",
        "secondary-fixed": "#9df5c3",
        "on-tertiary-fixed-variant": "#802a00",
        "on-secondary-fixed-variant": "#005233",
        "surface-container-high": "#e7e7f3",
        "tertiary-fixed": "#ffdbcf",
        error: "#ba1a1a",
        primary: "#003fb1",
        "on-secondary": "#ffffff",
        "text-muted": "#64748b",
        "primary-fixed-dim": "#b5c4ff",
        "outline-variant": "#c3c5d7",
        "on-surface-variant": "#434654",
        "on-error-container": "#93000a",
        surface: "#ffffff",
        "primary-container": "#1a56db",
        "primary-fixed": "#dbe1ff",
        "surface-bright": "#faf8ff",
        secondary: "#016c45",
        outline: "#737686",
        "on-primary": "#ffffff",
        "secondary-container": "#9af2c0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        none: "0",
        xs: "0.125rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        xs: "0 1px 2px rgba(0,0,0,0.03)",
        sm: "0 1px 3px rgba(0,0,0,0.05), 0 1px 2px rgba(0,0,0,0.02)",
        md: "0 2px 4px rgba(0,0,0,0.05), 0 1px 2px rgba(0,0,0,0.02)",
        lg: "0 4px 8px rgba(0,0,0,0.06), 0 2px 4px rgba(0,0,0,0.02)",
        xl: "0 8px 16px rgba(0,0,0,0.06), 0 4px 6px rgba(0,0,0,0.02)",
        "2xl": "0 12px 24px rgba(0,0,0,0.08)",
        inner: "inset 0 2px 4px rgba(0,0,0,0.05)",
        navbar: "0 1px 4px rgba(0,0,0,0.03)",
      },
      spacing: {
        margin: "2rem",
        gutter: "1.5rem",
        "page-x": "4.5rem",
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-sm-md": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-lg-xl": "2rem",
        "space-xl": "2.5rem",
        "space-4xl": "6rem",
        "header-h": "6.5rem",
      },
      fontWeight: {
        light: "300",
        regular: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
        extrabold: "800",
      },
      lineHeight: {
        none: "1",
        tight: "1.25",
        snug: "1.375",
        normal: "1.5",
        relaxed: "1.625",
        loose: "2",
      },
      letterSpacing: {
        tighter: "-0.05em",
        tight: "-0.025em",
        normal: "0em",
        wide: "0.025em",
        wider: "0.05em",
        widest: "0.1em",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-lg": ["Inter"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        "body-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", fontWeight: "700" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", fontWeight: "500" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "600" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", fontWeight: "500" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
